/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.VIEW;

import br.com.DTO.laboratorioDTO;
import java.awt.Graphics;
import java.awt.List;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author aluno.saolucas
 */
public class telaPrincipalVIEW extends javax.swing.JFrame {

    /**
     * Creates new form telaPrincipalVIEW
     */
    public telaPrincipalVIEW() {
        initComponents();

    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPrincipal = new javax.swing.JPanel();
        lblIMG = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        subMenuAdmintrador = new javax.swing.JRadioButtonMenuItem();
        Máquinas = new javax.swing.JMenu();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem5 = new javax.swing.JCheckBoxMenuItem();
        menuLaboratorios = new javax.swing.JMenu();
        subMenuaddLabin = new javax.swing.JRadioButtonMenuItem();
        jMenu5 = new javax.swing.JMenu();
        subMenuADDmanutencao = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        desktopPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        lblIMG.setBackground(new java.awt.Color(255, 255, 255));
        lblIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logocsl.jpg"))); // NOI18N

        javax.swing.GroupLayout desktopPrincipalLayout = new javax.swing.GroupLayout(desktopPrincipal);
        desktopPrincipal.setLayout(desktopPrincipalLayout);
        desktopPrincipalLayout.setHorizontalGroup(
            desktopPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(desktopPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopPrincipalLayout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addComponent(lblIMG)
                    .addContainerGap(100, Short.MAX_VALUE)))
        );
        desktopPrincipalLayout.setVerticalGroup(
            desktopPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
            .addGroup(desktopPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopPrincipalLayout.createSequentialGroup()
                    .addGap(58, 58, 58)
                    .addComponent(lblIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(48, Short.MAX_VALUE)))
        );

        jMenu1.setText("Cadastros");

        subMenuAdmintrador.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_DOWN_MASK));
        subMenuAdmintrador.setSelected(true);
        subMenuAdmintrador.setText("Usuário");
        subMenuAdmintrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuAdmintradorActionPerformed(evt);
            }
        });
        jMenu1.add(subMenuAdmintrador);

        jMenuBar1.add(jMenu1);

        Máquinas.setText("Máquinas");

        jCheckBoxMenuItem4.setSelected(true);
        jCheckBoxMenuItem4.setText("Adicionar máquina");
        jCheckBoxMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem4ActionPerformed(evt);
            }
        });
        Máquinas.add(jCheckBoxMenuItem4);

        jCheckBoxMenuItem5.setSelected(true);
        jCheckBoxMenuItem5.setText("Consultar todas");
        jCheckBoxMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem5ActionPerformed(evt);
            }
        });
        Máquinas.add(jCheckBoxMenuItem5);

        jMenuBar1.add(Máquinas);

        menuLaboratorios.setText("Laboratórios");

        subMenuaddLabin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        subMenuaddLabin.setSelected(true);
        subMenuaddLabin.setText("Adicionar Labin");
        subMenuaddLabin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuaddLabinActionPerformed(evt);
            }
        });
        menuLaboratorios.add(subMenuaddLabin);

        jMenuBar1.add(menuLaboratorios);

        jMenu5.setText("Manutenções");

        subMenuADDmanutencao.setSelected(true);
        subMenuADDmanutencao.setText("Adicionar manutenção");
        subMenuADDmanutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuADDmanutencaoActionPerformed(evt);
            }
        });
        jMenu5.add(subMenuADDmanutencao);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void subMenuAdmintradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuAdmintradorActionPerformed

        if (desktopPrincipal.getComponentCount() > 0) {
            desktopPrincipal.removeAll();  // Remove todos os componentes do painel
        }

        TelaAdministrador tadmin = new TelaAdministrador();
        desktopPrincipal.add(tadmin);
        tadmin.setVisible(true);
        lblIMG.setVisible(false);
        desktopPrincipal.revalidate(); 
        desktopPrincipal.repaint();


    }//GEN-LAST:event_subMenuAdmintradorActionPerformed

    private void jCheckBoxMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem4ActionPerformed

        if (desktopPrincipal.getComponentCount() > 0) {
            desktopPrincipal.removeAll();  // Remove todos os componentes do painel
        }

        telaAdicionarMaquinasVIEW telaaddmq = new telaAdicionarMaquinasVIEW();
        desktopPrincipal.add(telaaddmq);
        telaaddmq.setVisible(true);
        lblIMG.setVisible(false);
        desktopPrincipal.revalidate();
        desktopPrincipal.repaint();

    }//GEN-LAST:event_jCheckBoxMenuItem4ActionPerformed

    private void jCheckBoxMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem5ActionPerformed

        if (desktopPrincipal.getComponentCount() > 0) {
            desktopPrincipal.removeAll();  // Remove todos os componentes do painel
        }

        telaConsultarMaquinasVIEW telaconsulta = new telaConsultarMaquinasVIEW();
        desktopPrincipal.add(telaconsulta);
        telaconsulta.setVisible(true);
        lblIMG.setVisible(false);
        desktopPrincipal.revalidate();
        desktopPrincipal.repaint();

    }//GEN-LAST:event_jCheckBoxMenuItem5ActionPerformed

    private void subMenuaddLabinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuaddLabinActionPerformed
        
        
        if (desktopPrincipal.getComponentCount() > 0) {
            desktopPrincipal.removeAll();  // Remove todos os componentes do painel
        }

        TelaADDlabin addlabin = new TelaADDlabin();
        desktopPrincipal.add(addlabin);
        addlabin.setVisible(true);
        lblIMG.setVisible(false);
        desktopPrincipal.revalidate();
        desktopPrincipal.repaint();

        
    }//GEN-LAST:event_subMenuaddLabinActionPerformed

    private void subMenuADDmanutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuADDmanutencaoActionPerformed
         if (desktopPrincipal.getComponentCount() > 0) {
            desktopPrincipal.removeAll();  // Remove todos os componentes do painel
        }

        telaADDmanutencao addmanutencao = new telaADDmanutencao();
        desktopPrincipal.add(addmanutencao);
        addmanutencao.setVisible(true);
        lblIMG.setVisible(false);
        desktopPrincipal.revalidate();
        desktopPrincipal.repaint();
    }//GEN-LAST:event_subMenuADDmanutencaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPrincipalVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Máquinas;
    private javax.swing.JPanel desktopPrincipal;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblIMG;
    public static javax.swing.JLabel lblNome;
    private javax.swing.JMenu menuLaboratorios;
    private javax.swing.JRadioButtonMenuItem subMenuADDmanutencao;
    private javax.swing.JRadioButtonMenuItem subMenuAdmintrador;
    private javax.swing.JRadioButtonMenuItem subMenuaddLabin;
    // End of variables declaration//GEN-END:variables
}
