/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.VIEW;

import br.com.DAO.conexaoDAO;
import br.com.DAO.manutencaoDAO;
import br.com.DAO.maquinaDAO;
import br.com.DAO.usuarioDAO;
import br.com.DTO.UsuarioDTO;
import br.com.DTO.manutencaoDTO;
import br.com.DTO.maquinaDTO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Otávio
 */
public class telaADDmanutencao extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public telaADDmanutencao() {
        initComponents();
        conexao = conexaoDAO.conector();

        maquinaDAO mdao = new maquinaDAO();
        mdao.preencherCaixa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIDmanutencao = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        caixaStatus = new javax.swing.JComboBox<>();
        caixaTipo = new javax.swing.JComboBox<>();
        caixaIDeq = new javax.swing.JComboBox<>();
        btnAdicionar = new javax.swing.JButton();
        Editar = new javax.swing.JButton();

        jButton4.setText("jButton4");

        jLabel1.setText("ID");

        jLabel2.setText("Data");

        jLabel3.setText("Hora");

        jLabel6.setText("ID do equipamento");

        caixaStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o tipo", "Trocando peças", "Fazendo a limpeza", "Em manutenção no sistema" }));
        caixaStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaStatusActionPerformed(evt);
            }
        });

        caixaTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o status", "Em andamento", "Pendente", "Pronto" }));

        caixaIDeq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o ID da máquina" }));
        caixaIDeq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaIDeqActionPerformed(evt);
            }
        });

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(caixaIDeq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHora))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtIDmanutencao, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(caixaTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(caixaStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Editar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIDmanutencao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Editar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(caixaStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(caixaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(caixaIDeq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed

        String IDtext = txtIDmanutencao.getText();
        String dataString = txtData.getText();
        String hora = txtHora.getText();
        String tipo = (String) caixaTipo.getSelectedItem();
        String status = (String) caixaStatus.getSelectedItem();
        String Id_eq = (String) caixaIDeq.getSelectedItem();

        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
        java.sql.Date dataSQL = null;

        if (IDtext.isEmpty() || dataString.isEmpty() || hora.isEmpty() || tipo.equals("Selecione o tipo") || status.equals("Selecione o status") || Id_eq.equals("Selecione o ID da máquina")) {
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos!!!");
        }

        int ID = Integer.parseInt(IDtext);
       

        try {
            Date data = formatador.parse(dataString);
            dataSQL = new java.sql.Date(data.getTime());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data inválida. Formato esperado: dd-MM-yyyy", "Erro", JOptionPane.ERROR_MESSAGE);
        }

        manutencaoDTO mdto = new manutencaoDTO();
        mdto.setId_mn(ID);
        mdto.setData_mn(dataSQL);
        mdto.setHora_mn(hora);
        mdto.setTipo_mn(tipo);
        mdto.setStatus_mn(status);
        maquinaDTO maq = new maquinaDTO();
        maq.setId_eq(Integer.parseInt(Id_eq));

        manutencaoDAO mdao = new manutencaoDAO();
        mdao.adicionar(mdto);

//          maquinaDTO maqdto = new maquinaDTO();
//          maqdto.setStatus(tipo);

    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void caixaStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaStatusActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed

        int ID = Integer.parseInt(txtIDmanutencao.getText());
        String dataString = txtData.getText();
        String hora = txtHora.getText();
        String tipo = (String) caixaTipo.getSelectedItem();
        String status = (String) caixaStatus.getSelectedItem();
        String id_eq = (String) caixaIDeq.getSelectedItem();

        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
        Date data = null;

        try {
            data = formatador.parse(dataString);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data inválida. Formato esperado: dd-MM-yyyy", "Erro", JOptionPane.ERROR_MESSAGE);
        }

        manutencaoDTO mdto = new manutencaoDTO();
        mdto.setId_mn(ID);
        mdto.setData_mn((java.sql.Date) data);
        mdto.setHora_mn(hora);
        mdto.setTipo_mn(tipo);
        mdto.setStatus_mn(status);
        maquinaDTO maq = new maquinaDTO();
        maq.setId_eq(Integer.parseInt(id_eq));

        manutencaoDAO mdao = new manutencaoDAO();
        mdao.editar(mdto);


    }//GEN-LAST:event_EditarActionPerformed

    private void caixaIDeqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaIDeqActionPerformed

    }//GEN-LAST:event_caixaIDeqActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Editar;
    private javax.swing.JButton btnAdicionar;
    public static javax.swing.JComboBox<String> caixaIDeq;
    private javax.swing.JComboBox<String> caixaStatus;
    private javax.swing.JComboBox<String> caixaTipo;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtIDmanutencao;
    // End of variables declaration//GEN-END:variables
}
